services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app-network
  # chromadb:
  #   image: chromadb/chroma
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - chromadb_data:/data
  #   environment:
  #     - IS_PERSISTENT=TRUE
  #   healthcheck:
  #     test: ["CMD", "curl", "-f"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s 
  #   networks:
  #     - app-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9091:9091"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9091"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  eureka:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  doctor-service:
    image: doctor-service
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DOCKER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

  api-gateway:
    image: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      eureka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - app-network

  appointment-service:
    image: appointment-service
    ports:
      - "5959:5959"
    depends_on:
      eureka:
        condition: service_started
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DOCKER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9091
    networks:
      - app-network
  auth-service:
    image: auth-service
    ports:
      - "7979:7979"
    depends_on:
      eureka:
        condition: service_started
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_USERNAME}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DOCKER_DB_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9091
      SPRING_PROFILES_ACTIVE: docker 
    networks:
      - app-network
  ai-service:
    image: ai-service
    ports:
      - "7001:7001"
    depends_on:
       eureka:
          condition: service_started
      # - chromadb:
      #     condition: service_started


networks:
  app-network:
    driver: bridge
# rds pass wHk4tSHBTxrmKRmMYhDSZ
#  ecr 846210185519.dkr.ecr.ap-south-1.amazonaws.com/appointment-booking