services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  
  eureka:
    image: ${ECR_URL}/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - app-network

  
  api-gateway:
    image: ${ECR_URL}/api-gateway:latest
    ports:
      - "9000:9000"
    depends_on:
      eureka:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - app-network

  appointment-service:
    image: ${ECR_URL}/appointment-service:latest
    ports:
      - "5959:5959"
    depends_on:
      eureka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DOCKER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

  auth-service:
    image: ${ECR_URL}/auth-service:latest
    ports:
      - "7979:7979"
    depends_on:
      eureka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DOCKER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network
  ai-service:
    image: ai-service
    ports:
      - "7001:7001"
    depends_on:
      - eureka:
          condition: service_started
    entrypoint: 
       SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge