spring.application.name=ai-service
server.port=7001
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
# 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
spring.ai.openai.api-key=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
# mysql -h appointment-booking-db.c9ccmk8kuojl.ap-south-1.rds.amazonaws.com
#  -P 3306 -u admin -p --ssl-mode=VERIFY_IDENTITY --ssl-ca=./global-bundle.pem

