server.port=7001
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# spring.ai.openai.api-key=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
# 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