spring.profiles.active=dev
spring.application.name=ai-service
spring.ai.openai.api-key=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
rag-source-path=src/main/resources/rag.pdf
rag-ingest-on-startup=true
