spring.application.name=appointment-service

spring.ai.openai.api-key=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

# mysql -h appointment-booking-db.c9ccmk8kuojl.ap-south-1.rds.amazonaws.com
#  -P 3306 -u admin -p --ssl-mode=VERIFY_IDENTITY --ssl-ca=./global-bundle.pem

